[package]
name = "rustcraft-runtime"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
rustcraft-agent-api.workspace = true
rustcraft-bot-api.workspace = true
rustcraft-mod-api.workspace = true
rustcraft-content.workspace = true
rustcraft-engine-core.workspace = true
